<?php

namespace Proxies\__CG__\Alex\PizzaBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Pizza extends \Alex\PizzaBundle\Entity\Pizza implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNaam($naam)
    {
        $this->__load();
        return parent::setNaam($naam);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getNaam()
    {
        $this->__load();
        return parent::getNaam();
    }

    public function setOmschrijving($omschrijving)
    {
        $this->__load();
        return parent::setOmschrijving($omschrijving);
    }

    public function getOmschrijving()
    {
        $this->__load();
        return parent::getOmschrijving();
    }

    public function setBasisprijs($basisprijs)
    {
        $this->__load();
        return parent::setBasisprijs($basisprijs);
    }

    public function getBasisprijs()
    {
        $this->__load();
        return parent::getBasisprijs();
    }

    public function setExtras(\Alex\PizzaBundle\Entity\Extras $extras = NULL)
    {
        $this->__load();
        return parent::setExtras($extras);
    }

    public function getExtras()
    {
        $this->__load();
        return parent::getExtras();
    }

    public function addExtra(\Alex\PizzaBundle\Entity\Extras $extras)
    {
        $this->__load();
        return parent::addExtra($extras);
    }

    public function removeExtra(\Alex\PizzaBundle\Entity\Extras $extras)
    {
        $this->__load();
        return parent::removeExtra($extras);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'naam', 'omschrijving', 'basisprijs', 'extras');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}