<?php

namespace Proxies\__CG__\Alex\PizzaBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Bestelling extends \Alex\PizzaBundle\Entity\Bestelling implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setDatum($datum)
    {
        $this->__load();
        return parent::setDatum($datum);
    }

    public function getDatum()
    {
        $this->__load();
        return parent::getDatum();
    }

    public function setLevering($levering)
    {
        $this->__load();
        return parent::setLevering($levering);
    }

    public function getLevering()
    {
        $this->__load();
        return parent::getLevering();
    }

    public function setLeveringskost($leveringskost)
    {
        $this->__load();
        return parent::setLeveringskost($leveringskost);
    }

    public function getLeveringskost()
    {
        $this->__load();
        return parent::getLeveringskost();
    }

    public function setUser(\Alex\PizzaBundle\Entity\User $user)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setInitValue()
    {
        $this->__load();
        return parent::setInitValue();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'datum', 'levering', 'leveringskost', 'user');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}