<?php

namespace Alex\PizzaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BestellingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestellingRepository extends EntityRepository
{
}
