<?php

namespace Alex\PizzaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailsRepository extends EntityRepository
{
}
