<?php

namespace Alex\PizzaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PizzaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PizzaRepository extends EntityRepository
{
     public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AlexPizzaBundle:Pizza p ORDER BY p.name ASC'
            )
            ->getResult();
    }
}
