<?php

namespace Alex\PizzaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostnrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostnrRepository extends EntityRepository
{
     public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AlexPizzaBundle:Postnr p ORDER BY p.postnr ASC'
            )
            ->getResult();
    }
}
