alex_hello_homepage:
    pattern:  /
    defaults: { _controller: AlexHelloBundle:Hello:index }    
    
alex_hello_shop:
    path: /shop
    defaults: { _controller: AlexHelloBundle:Hello:shop }   
    
alex_hello_map:
    path: /map
    defaults: { _controller: AlexHelloBundle:Hello:map }  
    
AlexHelloBundle_extras:
        resource: "@AlexHelloBundle/Resources/config/routing/extras.yml"
        prefix:   /extras
        
AlexHelloBundle_kosten:
        resource: "@AlexHelloBundle/Resources/config/routing/kosten.yml"
        prefix:   /kosten
        
AlexHelloBundle_pizza:
        resource: "@AlexHelloBundle/Resources/config/routing/pizza.yml"
        prefix:   /pizza
        
AlexHelloBundle_postnr:
        resource: "@AlexHelloBundle/Resources/config/routing/postnr.yml"
        prefix:   /postnr

AlexHelloBundle_size:
        resource: "@AlexHelloBundle/Resources/config/routing/size.yml"
        prefix:   /size
        
AlexHelloBundle_type:
        resource: "@AlexHelloBundle/Resources/config/routing/type.yml"
        prefix:   /type
        
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    

    
